#!/usr/bin/env python3

from sys import argv, exit
from agent import Agent
from logger import Logger


def print_usage():
    print("Spyrai - a mirai C2 client")
    print("usage:")
    print("{} [host] [port]".format(argv[0]))

def main():
    l = Logger("main")
    if len(argv) != 3:
        print_usage()
        exit(-1)
    host, port = argv[1:]
    l.warn("Spyrai started.")
    spy = Agent(host, port)
    try:
        spy.Spy()
    except ConnectionResetError:
        l.error("Connection Reset.")
        exit(-2)
    except ConnectionRefusedError:
        l.error("Server refused our connection.")
    except KeyboardInterrupt:
        l.info("Goodbye.")
        l.info("stats: {commands} commands and {pong} pongs received.".format(
            **spy.stats))
        exit(0)

if __name__ == "__main__":
        main()
